import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/context/authContext";
import { ThemeProvider } from "@/context/themeProvider";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning className="dark">
            <body
                className={`${inter.variable} ${inter.variable} antialiased container mx-auto`}
            >
                <AuthProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    );
}
