import LeftSide from "@/components/auth/LeftSide";
import { BodyText } from "@/components/base/typography/BodyText";
import { Text } from "@/components/base/typography/TitleText";
import "@/styles/globals.css";
import type { Metadata } from "next";
import Image from "next/image";
import { title } from "process";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="flex flex-row min-h-screen w-full dark:bg-black bg-white
        ">
            <LeftSide></LeftSide>

            <div className="w-9/12 m-2 bg-white rounded-md flex justify-center items-center">
                {children}
            </div>
        </main>


    );
}
